version: "3"

dotenv: [".env"]

env:
  COMPOSE_PROJECT_NAME: '0l-{{.OL_ENV}}'  

tasks:
  checkout:
    desc: "Checkout libra-framework"
    cmd: |
      echo "Checking out '{{.OL_BRANCH}}' from '{{.OL_REPO}}' ..." \
        && git clone --branch {{.OL_BRANCH}} --depth 1 {{.OL_REPO}} {{.OL_SOURCE_DIR}} \
        && echo "Commit hash: $(git rev-parse HEAD)"
    ignore_error: true

  docker:build:
    desc: "Build docker images"
    deps: [checkout]
    cmds:
      - docker build -f Dockerfile --tag {{.OL_IMAGE}} {{.OL_ENV_DIR}}
      - task docker:build:source
      - task docker:build:builder

  docker:build:source:
    desc: "Build docker [source] image"
    deps: [checkout]
    cmds:
      - docker build -f Dockerfile --tag {{.OL_IMAGE}}-source --target source {{.OL_ENV_DIR}}

  docker:build:builder:
    desc: "Build docker [builder] image"
    cmds:
      - docker build -f Dockerfile --tag {{.OL_IMAGE}}-builder --target builder {{.OL_ENV_DIR}}

  docker:push:
    desc: "Push docker image"
    cmds:
      - docker push {{.OL_IMAGE}}

  docker:push:source:
    desc: "Push docker [source] image"
    cmds:
      - docker push {{.OL_IMAGE}}-source

  docker:push:builder:
    desc: "Push docker [builder] image"
    cmds:
      - docker push {{.OL_IMAGE}}-builder

  shell:
    desc: "Start a shell container"
    cmds:
      - docker compose up -d shell
      - docker compose exec shell bash

  source:
    desc: "Start a source container"
    cmds:
      - docker compose up -d source
      - docker compose exec source bash

  builder:
    desc: "Start a builder container"
    cmds:
      - docker compose up -d builder
      - docker compose exec builder bash

  clean:utils:
    desc: "Clean utility containers"
    cmds:
      - docker compose stop shell source builder
      - docker compose rm shell source builder

  clean:dirs:
    desc: "Clean env '{{.OL_ENV}}' directories"
    vars:
      OL_ENV_DIRS: "{{.OL_DATA_DIR}} {{.OL_SOURCE_DIR}} {{.OL_RECOVERY_DIR}}"
    cmds:
      - rm -rf {{.OL_ENV_DIR}}
      - for: { var: OL_ENV_DIRS }
        cmd: mkdir -p {{.ITEM}}
